# Base Image
FROM node:20-alpine3.18 as phase1

WORKDIR /app

# Run yarn only if package.json changes
# copied tsconfig as core-lib's tsconfig extends rootDir's tsconfig
COPY package.json .
COPY tsconfig.json .

# first create these directories, else the copying won't work.
RUN mkdir -p packages/core-lib
RUN mkdir -p apps/frontend

# copying only the required packages
COPY ./packages/core-lib/package.json packages/core-lib
COPY ./packages/core-lib packages/core-lib

COPY ./apps/frontend/package.json apps/frontend
COPY ./apps/frontend apps/frontend

# install node_modules
RUN npm install
RUN yarn lib:build

CMD [ "yarn", "workspace", "frontend", "dev" ]
