# Base Image
FROM node:20-alpine3.18 as phase1

WORKDIR /app

# Run yarn only if package.json changes
# copied tsconfig as core-lib's tsconfig extends rootDir's tsconfig
COPY package.json .
COPY tsconfig.json .

# first create these directories, else the copying won't work.
RUN mkdir -p packages/core-lib
RUN mkdir -p apps/react-client

# copying only the required packages
COPY ./packages/core-lib/package.json packages/core-lib
COPY ./packages/core-lib packages/core-lib

COPY ./apps/react-client/package.json apps/react-client
COPY ./apps/react-client apps/react-client

# install node_modules
RUN npm install
RUN yarn lib:build

CMD [ "yarn", "workspace", "react-client", "dev" ]
